import type { Config } from "vocs/config";

interface SidebarItem {
  collapsed?: boolean;
  items?: SidebarItem[];
  link?: string;
  text?: string;
}

const slug = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const title = (value: string) => {
  const moduleName = value.split("/").at(-1) ?? value;
  return moduleName
    .split("-")
    .map(
      (part) =>
        ({
          dns: "DNS",
          dnssec: "DNSSEC",
          ens: "ENS",
          erc: "ERC",
          eth: "ETH",
          hca: "HCA",
          l2: "L2",
          v1: "V1",
          v2: "V2",
        })[part] ?? part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join(" ");
};

const apiGroup = (base: string, text: string, names: ReadonlyArray<string>): SidebarItem => ({
  collapsed: true,
  items: names.map((name) => ({ link: `${base}/${slug(name)}`, text: name })),
  text,
});

const contractGroup = (text: string, modules: ReadonlyArray<string>): SidebarItem => ({
  collapsed: true,
  items: modules.map((module) => ({ link: `/contracts/api/${module}`, text: title(module) })),
  text,
});

const apiSectionsGroup = (
  base: string,
  text: string,
  groups: ReadonlyArray<{
    readonly path: string;
    readonly text: string;
    readonly names: ReadonlyArray<string>;
  }>,
): SidebarItem => ({
  collapsed: true,
  items: groups.flatMap((group) =>
    group.names.map((name) => ({
      link: `${base}${group.path}/${slug(name)}`,
      text: name,
    })),
  ),
  text,
});

const actionGroups = {
  batch: [
    "estimateCalls",
    "executeWritePlan",
    "getCallsStatus",
    "getWalletCapabilities",
    "prepareCalls",
    "readBatch",
    "readBatchSettled",
    "resumeCalls",
    "sendCalls",
    "simulateCalls",
  ],
  capabilities: [
    "getNameCapabilities",
    "getOperatorApproval",
    "getRecordPermissions",
    "getRegistryCapabilities",
    "getRegistryRoles",
    "getRequiredAuthorization",
    "getResolverCapabilities",
    "getResolverDelegateApproval",
    "getResolverRoles",
    "getTokenApproval",
    "getWrapperPermissions",
    "getWriteTarget",
    "hasRegistryRoles",
    "hasResolverRoles",
  ],
  dns: [
    "claimDnsName",
    "getDnsClaimStatus",
    "getDnsImportPlan",
    "getDnsRecord",
    "getDnsRecords",
    "getZoneHash",
    "hasDnsRecords",
    "importDnsName",
    "setDnsRecords",
    "setZoneHash",
  ],
  events: ["getEnsEvents", "getNameHistory", "watchEnsEvents"],
  migration: [
    "approveMigration",
    "getMigrationEligibility",
    "getMigrationPlan",
    "getMigrationStatus",
    "getMigrationTarget",
    "migrateName",
    "migrateNames",
  ],
  name: [
    "getOwner",
    "getNameState",
    "getExpiry",
    "getManager",
    "getNameStatus",
    "getProtocol",
    "getRegistrant",
    "getRegistry",
    "getTokenId",
    "isAvailable",
    "isMigrated",
    "isRenewable",
    "isReserved",
    "isWrapped",
    "getCanonicalResource",
  ],
  ownership: [
    "getTtl",
    "reclaimName",
    "setManager",
    "setTtl",
    "transferName",
    "transferRegistrant",
  ],
  permissions: [
    "approveName",
    "clearNameApproval",
    "grantRegistryRoles",
    "grantResolverRoles",
    "grantResolverRootRoles",
    "revokeRegistryRoles",
    "revokeResolverRoles",
    "revokeResolverRootRoles",
    "setOperatorApproval",
    "setRecordPermissions",
    "setResolverDelegateApproval",
  ],
  records: [
    "getRecords",
    "getText",
    "getTexts",
    "getAddress",
    "getAddresses",
    "getAvatar",
    "getContentHash",
    "getName",
    "getAbi",
    "getData",
    "getInterface",
    "getPubkey",
    "setRecords",
    "setText",
    "setTexts",
    "setAbi",
    "setAddress",
    "setAddresses",
    "setAlias",
    "setAvatar",
    "setContentHash",
    "setData",
    "setInterface",
    "setName",
    "setPubkey",
    "clearAvatar",
    "clearRecords",
  ],
  registration: [
    "registerName",
    "renewName",
    "getRegistrationPrice",
    "getRenewalPrice",
    "getRegistrationPlan",
    "getRegistrationParameters",
    "makeRegistrationCommitment",
    "getCommitmentStatus",
    "commitName",
    "completeRegistration",
    "registerNames",
    "renewNames",
    "isPaymentTokenSupported",
    "approvePaymentToken",
    "approveRenewalPayment",
  ],
  resolution: [
    "getResolver",
    "resolve",
    "resolveBatch",
    "resolveWithResolver",
    "getResolverVersion",
    "getAlias",
    "predictResolverAddress",
    "setResolver",
    "setResolverAndRecords",
    "getOrCreateResolver",
    "createResolver",
    "upgradeResolver",
  ],
  reverse: [
    "clearPrimaryName",
    "getPrimaryName",
    "setContractPrimaryName",
    "setPrimaryName",
    "setPrimaryNameForAddress",
  ],
  subnames: [
    "createSubname",
    "deleteSubname",
    "setSubnameExpiry",
    "setSubnameManager",
    "setSubnameRecord",
    "setSubnameResolver",
    "transferSubname",
  ],
  wrapping: [
    "extendSubnameExpiry",
    "getFuses",
    "getWrapperExpiry",
    "setChildFuses",
    "setFuses",
    "unwrapName",
    "wrapName",
  ],
} as const;
const hcaActionSections = [
  {
    path: "",
    text: "Account",
    names: [
      "prepareHcaCalls",
      "executeHcaCalls",
      "predictHcaAddress",
      "getHca",
      "getHcaOwner",
      "getHcaImplementation",
      "getHcaAccountId",
      "getHcaSessionNonce",
      "getAuthorizedHcaOwner",
      "getHcaImplementationApproval",
      "verifyHca",
      "getHcaCapabilities",
      "deployHca",
      "getHcaExecutionStatus",
      "revokeHcaSessions",
      "waitForHcaExecution",
      "watchHcaExecution",
      "isHcaSessionEnabled",
      "enableHcaSession",
      "enableHcaSessionWithRefund",
      "startHcaRegistration",
      "getHcaRegistration",
      "resumeHcaRegistration",
      "cancelHcaRegistration",
      "getHcaEntryPoint",
      "getHcaDeposit",
      "getHcaNonce",
      "getHcaSigningDomain",
      "verifyHcaSignature",
      "getHcaValidators",
      "getHcaExecutors",
      "getHcaHook",
      "getHcaFallbackHandler",
      "getHcaRegistry",
      "isHcaModuleInstalled",
      "supportsHcaExecutionMode",
      "addHcaDeposit",
      "withdrawHcaDeposit",
      "getHcaUpgradeEligibility",
      "upgradeHca",
      "isHcaImplementationTrusted",
      "getHcaUpgradeImplementationApproval",
    ],
  },
  {
    path: "/admin",
    text: "Governance",
    names: [
      "setHcaFactoryImplementationApproval",
      "setHcaUpgradeImplementationApproval",
      "setTrustedHcaImplementation",
      "transferHcaGovernanceOwnership",
      "renounceHcaGovernanceOwnership",
      "grantTrustedHcaRoles",
      "revokeTrustedHcaRoles",
      "getHcaGovernanceOwner",
      "getTrustedHcaRoles",
    ],
  },
] as const;

const indexerActionGroups = {
  status: ["getIndexerStatus"],
  names: [
    "getDecodedName",
    "getIndexedName",
    "getNames",
    "getNamesForAddress",
    "getResolvedNamesForAddress",
    "getSubnames",
    "searchNames",
  ],
  records: ["getIndexedRecords", "getRecordHistory"],
  registrations: ["getRegistrations", "getRegistrationsForAddress"],
  registries: ["getRegistriesForAddress", "getRegistry", "getRegistryLabels", "getRegistryRoles"],
  resolvers: [
    "getIndexedResolver",
    "getResolverApprovals",
    "getResolverMetadata",
    "getResolversForAddress",
  ],
  history: ["getEvents", "getNameHistory", "getRegistrationHistory"],
} as const;
const indexerHookGroups = {
  status: ["useIndexerStatus"],
  names: [
    "useDecodedName",
    "useIndexedName",
    "useNames",
    "useNamesForAddress",
    "useResolvedNamesForAddress",
    "useSubnames",
    "useSearchNames",
  ],
  records: ["useIndexedRecords", "useRecordHistory"],
  registrations: ["useRegistrations", "useRegistrationsForAddress"],
  registries: [
    "useRegistriesForAddress",
    "useIndexedRegistry",
    "useRegistryLabels",
    "useIndexedRegistryRoles",
  ],
  resolvers: [
    "useIndexedResolver",
    "useResolverApprovals",
    "useResolverMetadata",
    "useResolversForAddress",
  ],
  history: ["useEvents", "useIndexedNameHistory", "useRegistrationHistory"],
} as const;

const indexerActionSections = [
  { path: "", text: "Status", names: indexerActionGroups.status },
  { path: "/names", text: "Names", names: indexerActionGroups.names },
  { path: "/records", text: "Records", names: indexerActionGroups.records },
  {
    path: "/registrations",
    text: "Registrations",
    names: indexerActionGroups.registrations,
  },
  { path: "/registries", text: "Registries", names: indexerActionGroups.registries },
  { path: "/resolvers", text: "Resolvers", names: indexerActionGroups.resolvers },
  { path: "/history", text: "History", names: indexerActionGroups.history },
] as const;

const indexerHookSections = [
  { path: "", text: "Status", names: indexerHookGroups.status },
  { path: "/names", text: "Names", names: indexerHookGroups.names },
  { path: "/records", text: "Records", names: indexerHookGroups.records },
  {
    path: "/registrations",
    text: "Registrations",
    names: indexerHookGroups.registrations,
  },
  { path: "/registries", text: "Registries", names: indexerHookGroups.registries },
  { path: "/resolvers", text: "Resolvers", names: indexerHookGroups.resolvers },
  { path: "/history", text: "History", names: indexerHookGroups.history },
] as const;
const hookGroups = {
  context: ["useEnsforge", "useEnsforgeRegistry"],
  cache: ["useInvalidate"],
  batch: [
    "useReadBatch",
    "useReadBatchSettled",
    "useEstimateCalls",
    "useCallsStatus",
    "useWalletCapabilities",
    "usePrepareCalls",
    "useSimulateCalls",
    "useExecuteWritePlan",
    "useResumeCalls",
    "useSendCalls",
  ],
  capabilities: [
    "useNameCapabilities",
    "useOperatorApproval",
    "useRecordPermissions",
    "useRegistryCapabilities",
    "useRegistryRoles",
    "useRequiredAuthorization",
    "useResolverCapabilities",
    "useResolverDelegateApproval",
    "useResolverRoles",
    "useTokenApproval",
    "useWrapperPermissions",
    "useWriteTarget",
    "useHasRegistryRoles",
    "useHasResolverRoles",
  ],
  dns: [
    "useDnsClaimStatus",
    "useDnsImportPlan",
    "useDnsRecord",
    "useDnsRecords",
    "useZoneHash",
    "useHasDnsRecords",
    "useClaimDnsName",
    "useImportDnsName",
    "useSetDnsRecords",
    "useSetZoneHash",
  ],
  events: ["useEnsEvents", "useNameHistory", "useWatchEnsEvents"],
  migration: [
    "useMigrationEligibility",
    "useMigrationPlan",
    "useMigrationStatus",
    "useMigrationTarget",
    "useApproveMigration",
    "useMigrateName",
    "useMigrateNames",
  ],
  name: [
    "useOwner",
    "useNameState",
    "useNameStatus",
    "useExpiry",
    "useManager",
    "useProtocol",
    "useRegistrant",
    "useRegistry",
    "useTokenId",
    "useIsAvailable",
    "useIsMigrated",
    "useIsRenewable",
    "useIsReserved",
    "useIsWrapped",
    "useCanonicalResource",
  ],
  ownership: [
    "useTtl",
    "useReclaimName",
    "useSetManager",
    "useSetTtl",
    "useTransferName",
    "useTransferRegistrant",
  ],
  permissions: [
    "useApproveName",
    "useClearNameApproval",
    "useGrantRegistryRoles",
    "useGrantResolverRoles",
    "useGrantResolverRootRoles",
    "useRevokeRegistryRoles",
    "useRevokeResolverRoles",
    "useRevokeResolverRootRoles",
    "useSetOperatorApproval",
    "useSetRecordPermissions",
    "useSetResolverDelegateApproval",
  ],
  records: [
    "useRecords",
    "useText",
    "useTexts",
    "useAddress",
    "useAddresses",
    "useAvatar",
    "useContentHash",
    "useNameRecord",
    "useAbi",
    "useData",
    "useInterface",
    "usePubkey",
    "useSetRecords",
    "useSetText",
    "useSetTexts",
    "useClearAvatar",
    "useClearRecords",
    "useSetAbi",
    "useSetAddress",
    "useSetAddresses",
    "useSetAlias",
    "useSetAvatar",
    "useSetContentHash",
    "useSetData",
    "useSetInterface",
    "useSetName",
    "useSetPubkey",
  ],
  registration: [
    "useRegisterName",
    "useRenewName",
    "useRegistrationPrice",
    "useRenewalPrice",
    "useRegistrationPlan",
    "useRegistrationParameters",
    "useRegistrationCommitment",
    "useCommitmentStatus",
    "useCommitName",
    "useCompleteRegistration",
    "useRegisterNames",
    "useRenewNames",
    "useIsPaymentTokenSupported",
    "useApprovePaymentToken",
    "useApproveRenewalPayment",
  ],
  resolution: [
    "useResolver",
    "useResolve",
    "useResolveBatch",
    "useResolveWithResolver",
    "useResolverVersion",
    "useAlias",
    "usePredictResolverAddress",
    "useSetResolver",
    "useSetResolverAndRecords",
    "useGetOrCreateResolver",
    "useCreateResolver",
    "useUpgradeResolver",
  ],
  reverse: [
    "usePrimaryName",
    "useClearPrimaryName",
    "useSetContractPrimaryName",
    "useSetPrimaryName",
    "useSetPrimaryNameForAddress",
  ],
  subnames: [
    "useCreateSubname",
    "useDeleteSubname",
    "useSetSubnameExpiry",
    "useSetSubnameManager",
    "useSetSubnameRecord",
    "useSetSubnameResolver",
    "useTransferSubname",
  ],
  wrapping: [
    "useFuses",
    "useWrapperExpiry",
    "useExtendSubnameExpiry",
    "useSetChildFuses",
    "useSetFuses",
    "useUnwrapName",
    "useWrapName",
  ],
} as const;
const contractGroups = {
  deployments: [
    "deployments/mainnet-v1",
    "deployments/sepolia-v1",
    "deployments/sepolia-v2",
    "deployments/types",
  ],
  shared: [
    "shared/erc1155",
    "shared/erc165",
    "shared/erc20",
    "shared/erc721",
    "shared/fragments/erc20",
    "shared/universal-resolver",
  ],
  resolverProfiles: [
    "shared/resolver-profiles/abi",
    "shared/resolver-profiles/addr",
    "shared/resolver-profiles/contenthash",
    "shared/resolver-profiles/data",
    "shared/resolver-profiles/dns-record",
    "shared/resolver-profiles/dns-zone",
    "shared/resolver-profiles/extended-resolver",
    "shared/resolver-profiles/interface",
    "shared/resolver-profiles/multicall",
    "shared/resolver-profiles/name",
    "shared/resolver-profiles/pubkey",
    "shared/resolver-profiles/text",
    "shared/resolver-profiles/versionable",
  ],
  v1Abis: [
    "v1/abis/base-registrar",
    "v1/abis/bulk-renewal",
    "v1/abis/default-reverse-registrar",
    "v1/abis/dns-registrar",
    "v1/abis/dnssec-oracle",
    "v1/abis/ens-registry",
    "v1/abis/eth-registrar-controller",
    "v1/abis/l2-reverse-registrar",
    "v1/abis/name-wrapper-upgrade",
    "v1/abis/name-wrapper",
    "v1/abis/offchain-dns-resolver",
    "v1/abis/price-oracle",
    "v1/abis/public-resolver",
    "v1/abis/reverse-registrar",
    "v1/abis/standalone-reverse-registrar",
    "v1/abis/universal-resolver",
    "v1/abis/wrapped-eth-registrar-controller",
  ],
  v1Fragments: [
    "v1/fragments/authorization",
    "v1/fragments/base-registrar",
    "v1/fragments/bulk-renewal",
    "v1/fragments/dns-registrar",
    "v1/fragments/ens-registry",
    "v1/fragments/eth-registrar-controller",
    "v1/fragments/expiry",
    "v1/fragments/name-wrapper",
    "v1/fragments/public-resolver",
    "v1/fragments/registration",
    "v1/fragments/resolution",
    "v1/fragments/reverse-registrar",
    "v1/fragments/universal-resolver",
  ],
  v1Constants: ["v1/constants/name-wrapper-fuses"],
  v2Abis: [
    "v2/abis/batch-registrar",
    "v2/abis/contract-namer",
    "v2/abis/default-reverse-registrar-adapter",
    "v2/abis/dns-v1-mirror-root-batch-registrar",
    "v2/abis/ens-v1-resolver",
    "v2/abis/ens-v2-resolver",
    "v2/abis/eth-registrar",
    "v2/abis/eth-registry",
    "v2/abis/eth-renewer-v1",
    "v2/abis/graveyard",
    "v2/abis/label-store",
    "v2/abis/locked-migration-controller",
    "v2/abis/managed-universal-resolver-proxy",
    "v2/abis/migration-helper",
    "v2/abis/permissioned-resolver",
    "v2/abis/public-resolver-set",
    "v2/abis/public-resolver",
    "v2/abis/registry-upgrade-set",
    "v2/abis/reverse-registrar-adapter",
    "v2/abis/root-registry",
    "v2/abis/standard-rent-price-oracle",
    "v2/abis/universal-resolver",
    "v2/abis/unlocked-migration-controller",
    "v2/abis/upgradable-universal-resolver-proxy",
    "v2/abis/user-registry",
    "v2/abis/verifiable-factory",
    "v2/abis/wrapper-registry",
  ],
  v2Fragments: [
    "v2/fragments/authorization",
    "v2/fragments/contract-namer",
    "v2/fragments/default-reverse-registrar-adapter",
    "v2/fragments/eth-registrar",
    "v2/fragments/eth-registry",
    "v2/fragments/eth-renewer-v1",
    "v2/fragments/expiry",
    "v2/fragments/migration-helper",
    "v2/fragments/permissioned-registry",
    "v2/fragments/permissioned-resolver",
    "v2/fragments/registration",
    "v2/fragments/renewal",
    "v2/fragments/rent-price-oracle",
    "v2/fragments/resolution",
    "v2/fragments/standard-registry",
    "v2/fragments/tokenized-registry",
    "v2/fragments/universal-resolver",
    "v2/fragments/user-registry",
    "v2/fragments/verifiable-factory",
    "v2/fragments/wrapper-registry",
  ],
  v2Interfaces: [
    "v2/interfaces/address-set",
    "v2/interfaces/contract-name",
    "v2/interfaces/contract-namer",
    "v2/interfaces/enhanced-access-control",
    "v2/interfaces/erc1155-singleton",
    "v2/interfaces/eth-registrar",
    "v2/interfaces/eth-renewer",
    "v2/interfaces/l2-reverse-registrar",
    "v2/interfaces/label-store",
    "v2/interfaces/owned-registry",
    "v2/interfaces/permissioned-registry",
    "v2/interfaces/permissioned-resolver",
    "v2/interfaces/registry-events",
    "v2/interfaces/registry-uri-renderer",
    "v2/interfaces/registry",
    "v2/interfaces/rent-price-oracle",
    "v2/interfaces/standard-registry",
    "v2/interfaces/temporal-registry",
    "v2/interfaces/tokenized-registry",
    "v2/interfaces/universal-resolver",
    "v2/interfaces/universal-signature-validator",
    "v2/interfaces/wrapper-registry",
  ],
  v2Constants: [
    "v2/constants/registry-interfaces",
    "v2/constants/registry-roles",
    "v2/constants/resolver-interfaces",
    "v2/constants/resolver-roles",
  ],
  experimentalHca: [
    "v2/experimental/hca/hca-authorizer",
    "v2/experimental/hca/hca-funding-session-validator",
    "v2/experimental/hca/hca-owner-and-session-validator",
    "v2/experimental/hca/hca-upgrade-gate",
    "v2/experimental/hca/standalone-hca-factory-interface",
    "v2/experimental/hca/standalone-hca-factory",
    "v2/experimental/hca/standalone-hca-owner-interface",
    "v2/experimental/hca/standalone-single-owner-hca",
    "v2/experimental/hca/trusted-hca-set",
  ],
} as const;

export const sidebar = {
  "/hca/": [
    {
      text: "Introduction",
      items: [
        { link: "/hca/installation", text: "Installation" },
        { link: "/hca/getting-started", text: "Getting Started" },
      ],
    },
    {
      text: "Guides",
      items: [
        { link: "/hca/execution", text: "Execution Adapters" },
        { link: "/hca/providers", text: "Providers" },
        { link: "/hca/funding", text: "Cross-chain Funding" },
        { link: "/hca/remote", text: "Remote Registration" },
        { link: "/hca/examples", text: "Examples" },
        { link: "/hca/compatibility", text: "Compatibility" },
        { link: "/hca/release", text: "Release Checklist" },
      ],
    },
    {
      text: "API",
      items: [
        { link: "/hca/api/create-execution-adapter", text: "createExecutionAdapter" },
        { link: "/hca/api/pimlico", text: "pimlico" },
        { link: "/hca/api/rhinestone", text: "rhinestone" },
        { link: "/hca/api/create-hca-remote-handler", text: "createHcaRemoteHandler" },
        {
          link: "/hca/api/create-remote-hca-registration-actions",
          text: "createRemoteHcaRegistrationActions",
        },
      ],
    },
  ],
  "/core/": [
    {
      items: [
        { link: "/core/why", text: "Why ensforge" },
        { link: "/core/installation", text: "Installation" },
        { link: "/core/getting-started", text: "Getting Started" },
        { link: "/core/effect", text: "Effect" },
      ],
      text: "Introduction",
    },
    {
      items: [
        { link: "/core/guides/effect", text: "Effect" },
        { link: "/core/guides/error-handling", text: "Error Handling" },
        { link: "/core/guides/batching", text: "Batching" },
        { link: "/core/guides/protocol-routing", text: "Protocol Routing" },
        { link: "/core/guides/writes", text: "Writes" },
        { link: "/core/guides/hca", text: "HCA" },
        { link: "/core/guides/hca-registration", text: "HCA Registration" },
        { link: "/core/guides/workflow-storage", text: "Workflow Storage" },
        { link: "/core/guides/faq", text: "FAQ" },
      ],
      text: "Guides",
    },
    {
      items: [
        { link: "/core/api/create-config", text: "createConfig" },
        { link: "/core/api/create-wagmi-config", text: "createWagmiConfig" },
        { link: "/core/api/config", text: "Config" },
      ],
      text: "Configuration",
    },
    {
      items: [
        { link: "/core/api/actions", text: "Actions" },
        { link: "/core/api/schemas", text: "Schemas" },
        { link: "/core/api/errors", text: "Errors" },
        { link: "/core/api/write-plans", text: "Write Plans" },
      ],
      text: "API",
    },
    {
      collapsed: true,
      items: [
        { link: "/core/api/names", text: "Overview" },
        { link: "/core/api/names/normalize-name", text: "normalizeName" },
        { link: "/core/api/names/normalize-label", text: "normalizeLabel" },
        { link: "/core/api/names/analyze-name", text: "analyzeName" },
        { link: "/core/api/names/namehash", text: "namehash" },
        { link: "/core/api/names/labelhash", text: "labelhash" },
        { link: "/core/api/names/dns-encode-name", text: "dnsEncodeName" },
        { link: "/core/api/names/dns-decode-name", text: "dnsDecodeName" },
        { link: "/core/api/names/encode-address-record", text: "encodeAddressRecord" },
        { link: "/core/api/names/decode-address-record", text: "decodeAddressRecord" },
        { link: "/core/api/names/encode-content-hash", text: "encodeContentHash" },
        { link: "/core/api/names/decode-content-hash", text: "decodeContentHash" },
        { link: "/core/api/names/to-coin-type", text: "toCoinType" },
        { link: "/core/api/names/from-coin-type", text: "fromCoinType" },
      ],
      text: "Name Utilities",
    },
    apiGroup("/core/api/actions/name", "Name Actions", actionGroups.name),
    apiGroup("/core/api/actions/records", "Records Actions", actionGroups.records),
    apiGroup("/core/api/actions/resolution", "Resolution Actions", actionGroups.resolution),
    apiGroup("/core/api/actions/reverse", "Reverse Actions", actionGroups.reverse),
    apiGroup("/core/api/actions/registration", "Registration Actions", actionGroups.registration),
    apiGroup("/core/api/actions/subnames", "Subnames Actions", actionGroups.subnames),
    apiGroup("/core/api/actions/ownership", "Ownership Actions", actionGroups.ownership),
    apiGroup("/core/api/actions/capabilities", "Capabilities Actions", actionGroups.capabilities),
    apiGroup("/core/api/actions/batch", "Batch Actions", actionGroups.batch),
    apiGroup("/core/api/actions/migration", "Migration Actions", actionGroups.migration),
    apiGroup("/core/api/actions/dns", "DNS Actions", actionGroups.dns),
    apiGroup("/core/api/actions/permissions", "Permissions Actions", actionGroups.permissions),
    apiGroup("/core/api/actions/wrapping", "Wrapping Actions", actionGroups.wrapping),
    apiGroup("/core/api/actions/events", "Events Actions", actionGroups.events),
    apiSectionsGroup("/core/api/actions/indexer", "Indexer Actions", indexerActionSections),
    apiSectionsGroup("/core/api/actions/hca", "HCA Methods", hcaActionSections),
    apiGroup("/core/api/actions/workflows", "Workflows", [
      "getWorkflow",
      "reconcileWorkflowSubmission",
      "listWorkflows",
    ]),
  ],
  "/sdk/": [
    {
      items: [
        { link: "/sdk/why", text: "Why ensforge" },
        { link: "/sdk/installation", text: "Installation" },
        { link: "/sdk/getting-started", text: "Getting Started" },
        { link: "/sdk/effect", text: "Effect" },
      ],
      text: "Introduction",
    },
    {
      items: [
        { link: "/sdk/guides/grouped-actions", text: "Grouped Actions" },
        { link: "/sdk/guides/batching", text: "Batching" },
        { link: "/sdk/guides/error-handling", text: "Error Handling" },
        { link: "/sdk/guides/writes", text: "Writes" },
        { link: "/sdk/guides/hca", text: "HCA" },
        { link: "/core/guides/workflow-storage", text: "Workflow Storage" },
        { link: "/sdk/guides/faq", text: "FAQ" },
      ],
      text: "Guides",
    },
    {
      items: [
        { link: "/sdk/api/ensforge", text: "Ensforge" },
        { link: "/sdk/api/create-ensforge", text: "createEnsforge" },
      ],
      text: "Configuration",
    },
    apiGroup("/sdk/api/name", "Name Methods", actionGroups.name),
    apiGroup("/sdk/api/records", "Records Methods", actionGroups.records),
    apiGroup("/sdk/api/resolution", "Resolution Methods", actionGroups.resolution),
    apiGroup("/sdk/api/reverse", "Reverse Methods", actionGroups.reverse),
    apiGroup("/sdk/api/registration", "Registration Methods", actionGroups.registration),
    apiGroup("/sdk/api/subnames", "Subnames Methods", actionGroups.subnames),
    apiGroup("/sdk/api/ownership", "Ownership Methods", actionGroups.ownership),
    apiGroup("/sdk/api/capabilities", "Capabilities Methods", actionGroups.capabilities),
    apiGroup("/sdk/api/batch", "Batch Methods", actionGroups.batch),
    apiGroup("/sdk/api/migration", "Migration Methods", actionGroups.migration),
    apiGroup("/sdk/api/dns", "DNS Methods", actionGroups.dns),
    apiGroup("/sdk/api/permissions", "Permissions Methods", actionGroups.permissions),
    apiGroup("/sdk/api/wrapping", "Wrapping Methods", actionGroups.wrapping),
    apiGroup("/sdk/api/events", "Events Methods", actionGroups.events),
    apiSectionsGroup("/sdk/api/indexer", "Indexer Methods", indexerActionSections),
    apiSectionsGroup("/sdk/api/hca", "HCA Methods", hcaActionSections),
    apiGroup("/sdk/api/workflows", "Workflows", [
      "getWorkflow",
      "reconcileWorkflowSubmission",
      "listWorkflows",
    ]),
  ],
  "/react/": [
    {
      items: [
        { link: "/react/why", text: "Why ensforge" },
        { link: "/react/installation", text: "Installation" },
        { link: "/react/getting-started", text: "Getting Started" },
        { link: "/react/effect", text: "Effect" },
      ],
      text: "Introduction",
    },
    {
      items: [
        { link: "/react/guides/queries", text: "Query Hooks" },
        { link: "/react/guides/mutations", text: "Mutation Hooks" },
        { link: "/react/guides/hca", text: "HCA" },
        { link: "/react/guides/effect-atom", text: "Effect Atom" },
        { link: "/react/guides/caching", text: "Caching and Invalidation" },
        { link: "/react/guides/suspense", text: "Suspense" },
        { link: "/react/guides/batching", text: "Batching" },
        { link: "/react/guides/error-handling", text: "Error Handling" },
        { link: "/react/guides/ssr", text: "SSR and Frameworks" },
        { link: "/react/guides/faq", text: "FAQ" },
      ],
      text: "Guides",
    },
    {
      items: [
        { link: "/react/api/config", text: "Config" },
        { link: "/react/api/ensforge-provider", text: "EnsforgeProvider" },
        { link: "/react/api/atom-options", text: "Atom Options" },
        { link: "/react/api/atom-result", text: "Atom Result" },
        { link: "/react/api/mutation-options", text: "Mutation Options" },
        { link: "/react/api/mutation-result", text: "Mutation Result" },
      ],
      text: "Configuration",
    },
    {
      items: [
        { link: "/react/api/cache/create-registry", text: "createRegistry" },
        { link: "/react/api/cache/prefetch", text: "prefetch" },
        { link: "/react/api/cache/prefetch-effect", text: "prefetchEffect" },
        { link: "/react/api/cache/invalidate", text: "invalidate" },
        {
          link: "/react/api/cache/invalidate-effect",
          text: "invalidateEffect",
        },
        { link: "/react/api/cache/make-invalidation-keys", text: "makeInvalidationKeys" },
      ],
      text: "Cache",
    },
    apiGroup("/react/api/hooks/context", "Context Hooks", hookGroups.context),
    apiGroup("/react/api/hooks/name", "Name Hooks", hookGroups.name),
    apiGroup("/react/api/hooks/records", "Records Hooks", hookGroups.records),
    apiGroup("/react/api/hooks/resolution", "Resolution Hooks", hookGroups.resolution),
    apiGroup("/react/api/hooks/reverse", "Reverse Hooks", hookGroups.reverse),
    apiGroup("/react/api/hooks/registration", "Registration Hooks", hookGroups.registration),
    apiGroup("/react/api/hooks/subnames", "Subnames Hooks", hookGroups.subnames),
    apiGroup("/react/api/hooks/ownership", "Ownership Hooks", hookGroups.ownership),
    apiGroup("/react/api/hooks/capabilities", "Capabilities Hooks", hookGroups.capabilities),
    apiGroup("/react/api/hooks/batch", "Batch Hooks", hookGroups.batch),
    apiGroup("/react/api/hooks/cache", "Cache Hooks", hookGroups.cache),
    apiGroup("/react/api/hooks/migration", "Migration Hooks", hookGroups.migration),
    apiGroup("/react/api/hooks/dns", "DNS Hooks", hookGroups.dns),
    apiGroup("/react/api/hooks/permissions", "Permissions Hooks", hookGroups.permissions),
    apiGroup("/react/api/hooks/wrapping", "Wrapping Hooks", hookGroups.wrapping),
    apiGroup("/react/api/hooks/events", "Events Hooks", hookGroups.events),
    {
      collapsed: true,
      items: [
        { link: "/react/api/atoms/make-query-atom", text: "makeQueryAtom" },
        { link: "/react/api/atoms/make-mutation-atom", text: "makeMutationAtom" },
        { link: "/react/api/atoms/make-stream-atom", text: "makeStreamAtom" },
        { link: "/react/api/hooks/make-query-hook", text: "makeQueryHook" },
        { link: "/react/api/hooks/make-mutation-hook", text: "makeMutationHook" },
        {
          link: "/react/api/hooks/make-suspense-query-hook",
          text: "makeSuspenseQueryHook",
        },
        { link: "/react/api/hooks/prefetch-atom", text: "prefetchAtom" },
      ],
      text: "Advanced",
    },
    apiSectionsGroup("/react/api/hooks/indexer", "Indexer Hooks", indexerHookSections),
    apiGroup("/react/api/hooks/hca", "HCA Methods", [
      "useHca",
      "useHcaSuspense",
      "useHcaOwner",
      "useHcaOwnerSuspense",
      "useHcaImplementation",
      "useHcaImplementationSuspense",
      "useHcaAccountId",
      "useHcaAccountIdSuspense",
      "useHcaSessionNonce",
      "useHcaSessionNonceSuspense",
      "useAuthorizedHcaOwner",
      "useAuthorizedHcaOwnerSuspense",
      "useHcaImplementationApproval",
      "useHcaImplementationApprovalSuspense",
      "useVerifyHca",
      "useVerifyHcaSuspense",
      "useHcaCapabilities",
      "useHcaCapabilitiesSuspense",
      "usePredictHcaAddress",
      "usePredictHcaAddressSuspense",
      "useHcaEntryPoint",
      "useHcaEntryPointSuspense",
      "useHcaDeposit",
      "useHcaDepositSuspense",
      "useHcaNonce",
      "useHcaNonceSuspense",
      "useHcaSigningDomain",
      "useHcaSigningDomainSuspense",
      "useVerifyHcaSignature",
      "useVerifyHcaSignatureSuspense",
      "useHcaValidators",
      "useHcaValidatorsSuspense",
      "useHcaExecutors",
      "useHcaExecutorsSuspense",
      "useHcaHook",
      "useHcaHookSuspense",
      "useHcaFallbackHandler",
      "useHcaFallbackHandlerSuspense",
      "useHcaRegistry",
      "useHcaRegistrySuspense",
      "useIsHcaModuleInstalled",
      "useIsHcaModuleInstalledSuspense",
      "useSupportsHcaExecutionMode",
      "useSupportsHcaExecutionModeSuspense",
      "useHcaUpgradeEligibility",
      "useHcaUpgradeEligibilitySuspense",
      "useIsHcaImplementationTrusted",
      "useIsHcaImplementationTrustedSuspense",
      "useHcaUpgradeImplementationApproval",
      "useHcaUpgradeImplementationApprovalSuspense",
      "useHcaRegistration",
      "useHcaRegistrationSuspense",
      "useHcaExecutionStatus",
      "useHcaExecutionStatusSuspense",
      "useIsHcaSessionEnabled",
      "useIsHcaSessionEnabledSuspense",
      "useDeployHca",
      "usePrepareHcaCalls",
      "useExecuteHcaCalls",
      "useWaitForHcaExecution",
      "useEnableHcaSession",
      "useEnableHcaSessionWithRefund",
      "useRevokeHcaSessions",
      "useStartHcaRegistration",
      "useResumeHcaRegistration",
      "useCancelHcaRegistration",
      "useAddHcaDeposit",
      "useWithdrawHcaDeposit",
      "useUpgradeHca",
    ]),
    apiGroup("/react/api/hooks/workflows", "Workflow Hooks", [
      "useWorkflows",
      "useWorkflow",
      "useReconcileWorkflowSubmission",
    ]),
  ],
  "/contracts/": [
    {
      items: [
        { link: "/contracts/why", text: "Why ensforge" },
        { link: "/contracts/installation", text: "Installation" },
        { link: "/contracts/getting-started", text: "Getting Started" },
      ],
      text: "Introduction",
    },
    {
      items: [
        { link: "/contracts/guides/entrypoints", text: "Entrypoints" },
        { link: "/contracts/guides/deployments", text: "Deployments" },
        { link: "/contracts/guides/fragments", text: "ABI Fragments" },
        { link: "/contracts/guides/resolver-profiles", text: "Resolver Profiles" },
        { link: "/contracts/guides/faq", text: "FAQ" },
      ],
      text: "Guides",
    },
    contractGroup("Deployments", contractGroups.deployments),
    contractGroup("Shared", contractGroups.shared),
    contractGroup("Resolver Profiles", contractGroups.resolverProfiles),
    contractGroup("V1 ABIs", contractGroups.v1Abis),
    contractGroup("V1 Fragments", contractGroups.v1Fragments),
    contractGroup("V1 Constants", contractGroups.v1Constants),
    contractGroup("V2 ABIs", contractGroups.v2Abis),
    contractGroup("V2 Fragments", contractGroups.v2Fragments),
    contractGroup("V2 Interfaces", contractGroups.v2Interfaces),
    contractGroup("V2 Constants", contractGroups.v2Constants),
    contractGroup("Experimental HCA", contractGroups.experimentalHca),
  ],
} satisfies NonNullable<Config["sidebar"]>;
