import type { Abi } from "viem";

import type {
  hcaAuthorizerV2Abi,
  hcaFundingSessionValidatorV2Abi,
  hcaOwnerAndSessionValidatorV2Abi,
  hcaUpgradeGateV2Abi,
  standaloneHcaFactoryV2Abi,
  standaloneHcaFactoryV2InterfaceAbi,
  standaloneHcaOwnerV2InterfaceAbi,
  standaloneSingleOwnerHcaV2Abi,
  trustedHcaSetV2Abi,
} from "../v2/experimental/hca/index.js";

type FunctionNames<A extends Abi> = Extract<A[number], { readonly type: "function" }>["name"];
type Exposure = "action" | "inspection" | "internal" | "unsupported";

/** Public ABI availability is not permission to call a protocol callback or install a module. */
export const hcaAbiCoverage = {
  hcaAuthorizerV2Abi: {
    STANDALONE_HCA_FACTORY: "inspection",
  } satisfies Record<FunctionNames<typeof hcaAuthorizerV2Abi>, Exposure>,
  // Legacy source-account ABI; no verified deployment is enabled by the HCA profile.
  hcaFundingSessionValidatorV2Abi: {
    ACROSS_PERMIT2_CLAIM_SELECTOR: "unsupported",
    ERC7579_EMISSARY_EXECUTION_MODE: "unsupported",
    ERC7579_ERC1271_EMISSARY_EXECUTION_MODE: "unsupported",
    ERC7579_ERC1271_MODE: "unsupported",
    INTENT_EXECUTOR: "unsupported",
    PERMIT2: "unsupported",
    RHINESTONE_PROTOCOL_VERSION: "unsupported",
    ROUTER: "unsupported",
    isInitialized: "unsupported",
    isModuleType: "unsupported",
    isPermissionEnabled: "unsupported",
    isValidSignatureWithSender: "unsupported",
    onInstall: "unsupported",
    onUninstall: "unsupported",
    sessionConfig: "unsupported",
    validateUserOp: "unsupported",
    verifyExecution: "unsupported",
  } satisfies Record<FunctionNames<typeof hcaFundingSessionValidatorV2Abi>, Exposure>,
  hcaOwnerAndSessionValidatorV2Abi: {
    APPROVE_SELECTOR: "inspection",
    AUTHORIZE_NAME_ROLES_SELECTOR: "inspection",
    CLEAR_RECORDS_SELECTOR: "inspection",
    COMMIT_SELECTOR: "inspection",
    DEFAULT_REVERSE_REGISTRAR_HCA_ADAPTER: "inspection",
    DEPLOY_PROXY_SELECTOR: "inspection",
    ERC7579_EMISSARY_EXECUTION_MODE: "inspection",
    ERC7579_ERC1271_EMISSARY_EXECUTION_MODE: "inspection",
    ERC7579_ERC1271_MODE: "inspection",
    ETH_REGISTRAR: "inspection",
    GAS_REFUND_PAYMASTER: "inspection",
    INTENT_EXECUTOR: "inspection",
    MULTICALL_SELECTOR: "inspection",
    MULTICALL_WITH_NODE_CHECK_SELECTOR: "inspection",
    PAYMENT_TOKEN: "inspection",
    PERMITTED_RESOLVER_IMPL: "inspection",
    PERMIT_SELECTOR: "inspection",
    REGISTER_SELECTOR: "inspection",
    SECONDARY_PAYMENT_TOKEN: "inspection",
    SET_ABI_SELECTOR: "inspection",
    SET_ADDR_COIN_TYPE_SELECTOR: "inspection",
    SET_ADDR_SELECTOR: "inspection",
    SET_CONTENTHASH_SELECTOR: "inspection",
    SET_DATA_SELECTOR: "inspection",
    SET_INTERFACE_SELECTOR: "inspection",
    SET_NAME_SELECTOR: "inspection",
    SET_NAME_WITH_HCA_SELECTOR: "inspection",
    SET_PUBKEY_SELECTOR: "inspection",
    SET_TEXT_SELECTOR: "inspection",
    TRANSFER_FROM_SELECTOR: "inspection",
    VERIFIABLE_FACTORY: "inspection",
    VERIFIABLE_PROXY_LOGIC: "inspection",
    enableSession: "action",
    enableSessionWithRefund: "action",
    isInitialized: "inspection",
    isModuleType: "inspection",
    isPermissionEnabled: "inspection",
    isValidSignatureWithSender: "internal",
    onInstall: "internal",
    onUninstall: "internal",
    validateUserOp: "internal",
    verifyExecution: "internal",
  } satisfies Record<FunctionNames<typeof hcaOwnerAndSessionValidatorV2Abi>, Exposure>,
  hcaUpgradeGateV2Abi: {
    approvedImplementations: "inspection",
    owner: "inspection",
    renounceOwnership: "action",
    setImplementationApproval: "action",
    transferOwnership: "action",
  } satisfies Record<FunctionNames<typeof hcaUpgradeGateV2Abi>, Exposure>,
  standaloneHcaFactoryV2Abi: {
    VERIFIABLE_FACTORY: "inspection",
    approvedImplementations: "inspection",
    authorizedOwnerOf: "inspection",
    deploy: "action",
    deploymentSalt: "inspection",
    hcaOwners: "inspection",
    owner: "inspection",
    renounceOwnership: "action",
    setImplementationApproval: "action",
    transferOwnership: "action",
  } satisfies Record<FunctionNames<typeof standaloneHcaFactoryV2Abi>, Exposure>,
  standaloneHcaFactoryV2InterfaceAbi: {
    VERIFIABLE_FACTORY: "inspection",
    approvedImplementations: "inspection",
    authorizedOwnerOf: "inspection",
    deploy: "action",
    deploymentSalt: "inspection",
    hcaOwners: "inspection",
    setImplementationApproval: "action",
  } satisfies Record<FunctionNames<typeof standaloneHcaFactoryV2InterfaceAbi>, Exposure>,
  standaloneHcaOwnerV2InterfaceAbi: {
    owner: "inspection",
    ownerAndSessionNonce: "inspection",
  } satisfies Record<FunctionNames<typeof standaloneHcaOwnerV2InterfaceAbi>, Exposure>,
  standaloneSingleOwnerHcaV2Abi: {
    PREDECESSOR_UPGRADE_GATE: "inspection",
    UPGRADE_GATE: "inspection",
    accountId: "inspection",
    addDeposit: "action",
    canUpgradeFrom: "internal",
    checkERC7739Support: "inspection",
    eip712Domain: "inspection",
    // No hook is installed in this generation, and ordinary module changes are disabled.
    emergencyUninstallHook: "unsupported",
    entryPoint: "inspection",
    execute: "internal",
    executeByOwner: "action",
    executeComposable: "internal",
    executeFromExecutor: "internal",
    executeUserOp: "internal",
    getActiveHook: "inspection",
    getDeposit: "inspection",
    getExecutorsPaginated: "inspection",
    getFallbackHandlerBySelector: "inspection",
    getImplementation: "inspection",
    getRegistry: "inspection",
    getValidatorsPaginated: "inspection",
    initializeAccount: "internal",
    installModule: "unsupported",
    isInitialized: "inspection",
    isModuleInstalled: "inspection",
    isValidSignature: "inspection",
    nonce: "inspection",
    owner: "inspection",
    ownerAndSessionNonce: "inspection",
    proxiableUUID: "internal",
    revokeSessions: "action",
    // The pinned registry adapter disables configuration and attestation checks.
    setRegistry: "unsupported",
    supportsExecutionMode: "inspection",
    supportsModule: "inspection",
    uninstallModule: "unsupported",
    upgradeToAndCall: "action",
    validateUserOp: "internal",
    withdrawDepositTo: "action",
  } satisfies Record<FunctionNames<typeof standaloneSingleOwnerHcaV2Abi>, Exposure>,
  trustedHcaSetV2Abi: {
    ROOT_RESOURCE: "inspection",
    approve: "action",
    getAssigneeCount: "inspection",
    grantRoles: "action",
    grantRootRoles: "action",
    hasAssignees: "inspection",
    hasRoles: "inspection",
    hasRootRoles: "inspection",
    includes: "inspection",
    isContractNamer: "inspection",
    revokeRoles: "action",
    revokeRootRoles: "action",
    roleCount: "inspection",
    roles: "inspection",
    supportsInterface: "inspection",
  } satisfies Record<FunctionNames<typeof trustedHcaSetV2Abi>, Exposure>,
} as const;
